"""
Configurable stock universe — NIFTY 50 / 100 / 250.
Change ACTIVE_UNIVERSE below or in data/data_config.yaml to switch.
"""

NIFTY_50 = [
    "RELIANCE","HDFCBANK","ICICIBANK","TCS","INFY","BHARTIARTL",
    "SBIN","ITC","LT","KOTAKBANK","AXISBANK","BAJFINANCE",
    "TATAMOTORS","MARUTI","SUNPHARMA","HCLTECH","WIPRO",
    "TATASTEEL","NTPC","POWERGRID","COALINDIA","ONGC",
    "TITAN","ASIANPAINT","ULTRACEMCO","BAJAJFINSV","NESTLEIND",
    "TECHM","HINDALCO","HINDUNILVR","JSWSTEEL","ADANIPORTS",
    "DRREDDY","CIPLA","EICHERMOT","BRITANNIA","DIVISLAB",
    "HEROMOTOCO","BPCL","GRASIM","APOLLOHOSP","TRENT",
    "TATACONSUM","SBILIFE","HDFCLIFE","M&M","BAJAJ-AUTO",
    "SHREECEM","INDUSINDBK","IOC",
]

NIFTY_100_EXTRA = [
    "ADANIENT","ADANIGREEN","ADANIPOWER","AMBUJACEM","BANKBARODA",
    "BEL","BERGEPAINT","BOSCHLTD","CANBK","CHOLAFIN",
    "COLPAL","CONCOR","DABUR","DLF","GAIL",
    "GODREJCP","HAVELLS","HAL","ICICIPRULI","ICICIGI",
    "IDFCFIRSTB","INDHOTEL","IRCTC","IRFC","JINDALSTEL",
    "JSWENERGY","LTF","LTIM","LUPIN","MARICO",
    "MAXHEALTH","MOTHERSON","MUTHOOTFIN","NHPC","NYKAA",
    "OBEROIRLTY","PFC","PIDILITIND","PNB","POLYCAB",
    "RECLTD","SBICARD","SIEMENS","SRF","TORNTPHARM",
    "TVSMOTOR","UNITDSPR","VEDL","ZOMATO","ZYDUSLIFE",
]

NIFTY_250_EXTRA = [
    "AARTIIND","ABB","ABCAPITAL","ABFRL","ACC",
    "AJANTPHARM","ALKEM","APLAPOLLO","ASHOKLEY","ASTRAL",
    "ATUL","AUBANK","AUROPHARMA","BALKRISIND","BALRAMCHIN",
    "BANDHANBNK","BATAINDIA","BHEL","BIOCON","CANFINHOME",
    "CHAMBLFERT","CLEAN","COFORGE","CROMPTON","CUB",
    "CUMMINSIND","DEEPAKNTR","DELTACORP","DIXON","ESCORTS",
    "EXIDEIND","FEDERALBNK","FORTIS","GMRINFRA","GNFC",
    "GRANULES","GSPL","GUJGASLTD","HDFCAMC","HINDPETRO",
    "HONAUT","IBREALEST","IGL","INDUSTOWER","INTELLECT",
    "IOB","IPCA","JUBLFOOD","KALYANKJIL","KEI",
    "KPITTECH","LALPATHLAB","LAURUSLABS","LICHSGFIN","LTTS",
    "M&MFIN","MANAPPURAM","MFSL","MGL","MPHASIS",
    "MRF","NAM-INDIA","NATIONALUM","NAUKRI","NAVINFLUOR",
    "NMDC","OFSS","PAGEIND","PERSISTENT","PETRONET",
    "PIIND","PRESTIGE","PVR","RAMCOCEM","RBLBANK",
    "SAIL","SAPPHIRE","SOLARINDS","SONACOMS","STARHEALTH",
    "SUNDARMFIN","SUNDRMFAST","SUNTV","SUPREMEIND","SYNGENE",
    "TATACHEM","TATACOMM","TATAELXSI","TATAPOWER","THERMAX",
    "TIINDIA","TIMKEN","TRENT","TRIDENT","UBL",
    "UJJIVANSFB","UNIONBANK","UPL","VOLTAS","WHIRLPOOL",
]

# ═══ CONFIGURE YOUR UNIVERSE HERE ═══
# Options: "nifty50", "nifty100", "nifty250"
ACTIVE_UNIVERSE = "nifty50"

def get_universe(name=None):
    """Get stock list by universe name."""
    name = (name or ACTIVE_UNIVERSE).lower().replace(" ", "").replace("_", "")
    if name in ("nifty250", "250"):
        return NIFTY_50 + NIFTY_100_EXTRA + NIFTY_250_EXTRA
    elif name in ("nifty100", "100"):
        return NIFTY_50 + NIFTY_100_EXTRA
    else:  # default nifty50
        return NIFTY_50

DEFAULT_UNIVERSE = get_universe()
ALL_STOCKS = NIFTY_50 + NIFTY_100_EXTRA + NIFTY_250_EXTRA

STOCK_SECTORS = {
    "RELIANCE":"Energy","HDFCBANK":"Banking","ICICIBANK":"Banking","TCS":"IT",
    "INFY":"IT","SBIN":"Banking","BHARTIARTL":"Telecom","ITC":"FMCG",
    "KOTAKBANK":"Banking","LT":"Infra","AXISBANK":"Banking","TATAMOTORS":"Auto",
    "MARUTI":"Auto","SUNPHARMA":"Pharma","HCLTECH":"IT","WIPRO":"IT",
    "BAJFINANCE":"NBFC","TATASTEEL":"Metals","NTPC":"Power","POWERGRID":"Power",
    "COALINDIA":"Mining","ONGC":"Energy","TITAN":"Consumer","ASIANPAINT":"Consumer",
    "HAL":"Defence","BEL":"Defence","ZOMATO":"Tech","ADANIENT":"Infra",
}
