"""Configurable stock universe — NIFTY 50 / 100 / 250."""
import os
NIFTY_50 = ["RELIANCE","HDFCBANK","ICICIBANK","TCS","INFY","BHARTIARTL","SBIN","ITC","LT","KOTAKBANK","AXISBANK","BAJFINANCE","TATAMTRDVT","MARUTI","SUNPHARMA","HCLTECH","WIPRO","TATASTEEL","NTPC","POWERGRID","COALINDIA","ONGC","TITAN","ASIANPAINT","ULTRACEMCO","BAJAJFINSV","NESTLEIND","TECHM","HINDALCO","HINDUNILVR","JSWSTEEL","ADANIPORTS","DRREDDY","CIPLA","EICHERMOT","BRITANNIA","DIVISLAB","HEROMOTOCO","BPCL","GRASIM","APOLLOHOSP","TRENT","TATACONSUM","SBILIFE","HDFCLIFE","M&M","BAJAJ-AUTO","SHREECEM","INDUSINDBK","IOC"]
NIFTY_100_EXTRA = ["ADANIENT","ADANIGREEN","AMBUJACEM","BANKBARODA","BEL","BERGEPAINT","CANBK","CHOLAFIN","COLPAL","DABUR","DLF","GAIL","GODREJCP","HAVELLS","HAL","IDFCFIRSTB","INDHOTEL","IRCTC","IRFC","JINDALSTEL","LUPIN","MARICO","MAXHEALTH","MOTHERSON","MUTHOOTFIN","NHPC","OBEROIRLTY","PFC","PNB","POLYCAB","RECLTD","SIEMENS","SRF","TORNTPHARM","TVSMOTOR","VEDL","ZOMATO","ZYDUSLIFE"]
NIFTY_250_EXTRA = ["ABB","ABCAPITAL","ACC","ALKEM","ASHOKLEY","ASTRAL","ATUL","AUBANK","AUROPHARMA","BALKRISIND","BANDHANBNK","BATAINDIA","BHEL","BIOCON","CANFINHOME","COFORGE","CROMPTON","CUMMINSIND","DEEPAKNTR","DIXON","ESCORTS","EXIDEIND","FEDERALBNK","FORTIS","GMRINFRA","GRANULES","HDFCAMC","HINDPETRO","IGL","INDUSTOWER","IPCA","JUBLFOOD","KEI","KPITTECH","LALPATHLAB","LAURUSLABS","LICHSGFIN","LTTS","MANAPPURAM","MGL","MPHASIS","MRF","NAUKRI","NAVINFLUOR","NMDC","OFSS","PAGEIND","PERSISTENT","PETRONET","PIIND","PRESTIGE","RBLBANK","SAIL","STARHEALTH","SUNDARMFIN","SUNTV","TATACOMM","TATAELXSI","TATAPOWER","TIINDIA","TRIDENT","UBL","UNIONBANK","UPL","VOLTAS","WHIRLPOOL"]
ACTIVE_UNIVERSE = os.getenv("UNIVERSE", "nifty250")
def get_universe(name=None):
    name = (name or ACTIVE_UNIVERSE).lower().replace(" ","").replace("_","")
    if "250" in name: return NIFTY_50 + NIFTY_100_EXTRA + NIFTY_250_EXTRA
    elif "100" in name: return NIFTY_50 + NIFTY_100_EXTRA
    return NIFTY_50
DEFAULT_UNIVERSE = get_universe()
ALL_STOCKS = NIFTY_50 + NIFTY_100_EXTRA + NIFTY_250_EXTRA
STOCK_SECTORS = {"RELIANCE":"Energy","HDFCBANK":"Banking","TCS":"IT","INFY":"IT","SBIN":"Banking","ITC":"FMCG","TATAMOTORS":"Auto","HAL":"Defence","BEL":"Defence","ZOMATO":"Tech","TATASTEEL":"Metals","SUNPHARMA":"Pharma"}
